version: '3.3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  asteroid:
    build: .
    container_name: asteroid
    environment:
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=galaxy
      - SNAPSHOT_DIRECTORY=/usr/share/nginx/html/snapshots
      - SNAPSHOT_URL_PREFIX=http://asteroid/snapshots
      - SNAPSHOT_WAIT_INTERVAL=30
      - RABBITMQ_MAX_QUEUE_LENGTH=250
    ports:
      - "80:80"
    volumes:
      - ./snapshots:/usr/share/nginx/html/snapshots
    restart:
      always
    depends_on:
      - mongo
      - rabbitmq
      