rabbitmq_server:
  uri: amqp://guest:guest@localhost

mongodb:
  uri: mongodb://localhost:27017
  db: galaxy

snapshot:
  directory: /usr/share/nginx/html/snapshots
  url_prefix: http://localhost/snapshots